# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: laravel_app
#     restart: unless-stopped
#     working_dir: /var/www/html
#     environment:
#       - DB_CONNECTION=sqlsrv
#       - DB_HOST=host.docker.internal
#       - DB_PORT=1433
#       - DB_DATABASE=dbAsset
#       - DB_USERNAME=${DB_USERNAME:-sa}
#       - DB_PASSWORD=${DB_PASSWORD:-}
      
#       - DB_QUINARY_CONNECTION=sqlsrv
#       - DB_QUINARY_HOST=host.docker.internal
#       - DB_QUINARY_PORT=1433
#       - DB_QUINARY_DATABASE=dbAsrama
#       - DB_QUINARY_USERNAME=${DB_QUINARY_USERNAME:-sa}
#       - DB_QUINARY_PASSWORD=${DB_QUINARY_PASSWORD:-}
      
#       - DB_SECONDARY_CONNECTION=sqlsrv
#       - DB_SECONDARY_HOST=192.168.3.251
#       - DB_SECONDARY_PORT=85
#       - DB_SECONDARY_DATABASE=qualitydb
#       - DB_SECONDARY_USERNAME=${DB_SECONDARY_USERNAME:-}
#       - DB_SECONDARY_PASSWORD=${DB_SECONDARY_PASSWORD:-}
#     volumes:
#       - ./:/var/www/html
#     networks:
#       - laravel

#   nginx:
#     image: nginx:alpine
#     container_name: laravel_nginx
#     restart: unless-stopped
#     ports:
#       - "8000:80"
#       - "443:443"
#     volumes:
#       - ./:/var/www/html
#       - ./docker/nginx/conf.d:/etc/nginx/conf.d
#       - ./docker/nginx/ssl:/etc/nginx/ssl
#     networks:
#       - laravel
#     depends_on:
#       - app

#   redis:
#     image: redis:7-alpine
#     container_name: laravel_redis
#     restart: unless-stopped
#     ports:
#       - "6379:6379"
#     networks:
#       - laravel

# networks:
#   laravel:
#     driver: bridge
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/html
    environment:
      - DB_CONNECTION=sqlsrv
      - DB_HOST=mssql
      - DB_PORT=1433
      - DB_DATABASE=dbAsset
      - DB_USERNAME=SA
      - DB_PASSWORD=YourStrong@Password123
      
      - DB_QUINARY_CONNECTION=sqlsrv
      - DB_QUINARY_HOST=mssql
      - DB_QUINARY_PORT=1433
      - DB_QUINARY_DATABASE=dbAsrama
      - DB_QUINARY_USERNAME=SA
      - DB_QUINARY_PASSWORD=YourStrong@Password123
      
      - DB_SECONDARY_CONNECTION=sqlsrv
      - DB_SECONDARY_HOST=192.168.3.251
      - DB_SECONDARY_PORT=85
      - DB_SECONDARY_DATABASE=qualitydb
      - DB_SECONDARY_USERNAME=${DB_SECONDARY_USERNAME:-}
      - DB_SECONDARY_PASSWORD=${DB_SECONDARY_PASSWORD:-}
    volumes:
      - ./:/var/www/html
    networks:
      - laravel
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: laravel_mssql
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password123
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    networks:
      - laravel
    volumes:
      - mssql_data:/var/opt/mssql

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - laravel

  redis:
    image: redis:7-alpine
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge

volumes:
  mssql_data: